---
title: CV - Dingrui(Frank)
author: Dingrui(Frank) Zhang
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['custom_resume.css', 'styles_html.css', 'resume']
    # css: ['css/custom_resume.css', 'css/styles_pdf.css', 'resume']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
params:
  doctype: "HTML" # "PDF" or "HTML" is automatically updated in update_resume.R 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

#load packages
library(tidyverse)
library(readxl)
library(glue)

#source helper functions
source('helper_functions.R')


# get data from xlsx file
position_data <- readxl::read_excel('resume_data.xlsx', 
                                    sheet = "positions", 
                                    na = c("", "NA", "na")) 

skill_data <- readxl::read_excel('resume_data.xlsx', 
                                 sheet = "skills",
                                 na = c("", "NA", "na"))                                 
```


Aside
================================================================================


Contact {#contact}
--------------------------------------------------------------------------------


- <i class="fas fa-user"></i> Frank Zhang
- <i class="fa fa-phone"></i> +61 0414-350-521
- <i class="fa fa-envelope"></i> zhang@ding-rui.org
- <i class="fab fa-linkedin-in"></i> [Dingrui(Frank) Zhang](https://www.linkedin.com/in/dingrui-zhang/){target="_blank"}


```{r download, echo=FALSE}
# if doctype is html add link to download a pdf version
if(params$doctype == "HTML"){
  cat("[<i class='fas fa-download'></i> Download this vitae as a PDF](https://github.com/frankzhangsyd/vitae/raw/master/output/Frank-Zhang-CV.pdf)")
}

```



<br>


Skills {#Skills}
--------------------------------------------------------------------------------

**Data Analytics:**SQL, Python, R, Alteryx<br>
**Data Visualization:**PowerBI, Qlik, Tableau<br>
**Cloud:**AWS, GCP, Azure<br>
**Other Techniques:**Git, Devops, Excel, VBA, Javascript<br>
**Business Acumen**<br>
**Communication**<br>
**Leadership/Management**





<!-- Disclaimer {#disclaimer} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- This resume was created using the **R** language.    -->
<!-- Source code: [**Github repo**](https://github.com/frankzhangsyd/vitae){target="_blank"}. -->

<!-- Last updated on `r Sys.Date()`. -->
<!-- <br> -->
<!-- <br> -->


Main
================================================================================


Frank Zhang, CA {#title}
--------------------------------------------------------------------------------

* Seasoned data analytics/engineering expert and chartered accountant, boasting six years of experience in harnessing data for critical business insights and strategic decision-making.
* Proficient in the realms of data warehousing, ELT processes, data analysis, visualization, and crafting insightful business intelligence reports.
* Exhibits a robust blend of sharp analytical skills and business savvy, adept at addressing complex business challenges in collaboration with non-technical teams.
* Proven leadership abilities in steering data-focused teams and forging effective cross-functional collaborations.


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r education}
print_section(position_data, 'education')
```



Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r jobs}
print_section(position_data, 'work')
```



<i class="fas fa-rocket"></i> Professional Development/Projects
--------------------------------------------------------------------------------

```{r development}
print_section(position_data, 'development')
```


